// Typed access to the sanitized FA310 import (generated by
// scripts/buildFa310Seed.mjs from input/FA310/FA310.xls).
//
// These are Orbikt's FA310 DATA records (service contacts, matching, manager
// grouping) — NOT review results. FA310 review rules live in
// LongCare-QA-Engine and reach Orbikt only via the review adapter seam.

import records from "../../data/seed/fa310.generated.json";
import meta from "../../data/seed/fa310.meta.generated.json";

export interface Fa310Record {
  caseId: string | null; // surrogate case id, null when unmatched to CS100
  maskedNationalId: string | null;
  serviceDate: string | null; // ISO
  phoneVisit: boolean;
  homeVisit: boolean;
  // Governance data rule: only managerName / maskedManagerId / managerSource
  // may be exposed for the responsible manager (resolved at import time from
  // FA310 column S + input/manager-map/manager-map.csv).
  managerName: string | null;
  maskedManagerId: string | null;
  managerSource: "fa310" | "unresolved";
  hasTracking: boolean;
  hasGoals: boolean;
}

export interface Fa310Meta {
  source: string;
  cs100Source: string;
  managerMapSource: string;
  managerMapEntries: number;
  managerMapErrors: string[];
  sheet: string;
  generatedAt: string;
  totalRows: number;
  invalidRows: number;
  records: number;
  matchedCases: number;
  unmatchedRecords: number;
  unmatchedMaskedIds: string[];
  distinctManagers: number;
  byManagerName: Record<string, number>;
  unmappedManagerIds: string[];
  note: string;
}

export const fa310Records = records as Fa310Record[];
export const fa310Meta = meta as Fa310Meta;

/** The FA310 record for one case (the export carries one row per case). */
export function fa310ForCase(caseId: string): Fa310Record | undefined {
  return fa310Records.find((r) => r.caseId === caseId);
}
